/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Gamepad */

#ifndef _Included_Gamepad
#define _Included_Gamepad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Gamepad
 * Method:    getMaxGamepad
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Gamepad_getMaxGamepad
  (JNIEnv *, jclass);

/*
 * Class:     Gamepad
 * Method:    getState
 * Signature: (ILState;)I
 */
JNIEXPORT jint JNICALL Java_Gamepad_getState
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
